CREATE FUNCTION ed25519_password RETURNS STRING SONAME "auth_ed25519.so";

CREATE ROLE appsuper;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  appdb.* TO appsuper;

CREATE ROLE appuser;
GRANT CREATE TEMPORARY TABLES, EXECUTE ON appdb.* TO appuser;

CREATE USER 'appbroker'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'appbroker'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT appuser TO 'appbroker'@'%';
SET DEFAULT ROLE appuser FOR 'appbroker'@'%';

CREATE USER 'appsa'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'appsa'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  appdb.* TO 'appsa'@'%';

CREATE USER 'cdbsa'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'cdbsa'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  cdb.* TO 'cdbsa'@'%';

CREATE USER 'idbroker'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'idbroker'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, LOCK TABLES, EXECUTE, TRIGGER ON cid.* TO 'idbroker'@'%';

CREATE USER 'idsa'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'idsa'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  cid.* TO 'idsa'@'%';

CREATE USER 'loggingreader'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'loggingreader'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, CREATE TEMPORARY TABLES, EXECUTE ON WTFlogs.* TO 'loggingreader'@'%';

CREATE USER 'loggingsa'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'loggingsa'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  WTFlogs.* TO 'loggingsa'@'%';

CREATE USER 'loggingwriter'@'%' IDENTIFIED WITH mysql_native_password;
SET PASSWORD FOR 'loggingwriter'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT SELECT, INSERT, CREATE TEMPORARY TABLES, EXECUTE ON WTFlogs.* TO 'loggingwriter'@'%';

CREATE USER 'sa'@'%' IDENTIFIED WITH mysql_native_password;
GRANT USAGE ON *.* TO 'sa'@'%'
WITH GRANT OPTION;
SET PASSWORD FOR 'sa'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DELETE HISTORY, DROP, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'sa'@'%';
GRANT appuser TO 'sa'@'%' WITH ADMIN OPTION;

CREATE USER 'sasmp'@'%' IDENTIFIED WITH mysql_native_password;
GRANT USAGE ON *.* TO 'sasmp'@'%'
WITH GRANT OPTION;
SET PASSWORD FOR 'sasmp'@'%' = '*06F4C35DA89E947A3B84F4672C90DF44D3085F2F';
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DELETE HISTORY, DROP, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'sasmp'@'%';
GRANT appuser TO 'sasmp'@'%' WITH ADMIN OPTION;
