CREATE OR REPLACE ROLE appsuper;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  appdb.* TO appsuper;

CREATE OR REPLACE ROLE appuser;
GRANT CREATE TEMPORARY TABLES, EXECUTE ON appdb.* TO appuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE appdb.TGO_trivial_table_v TO appuser;

CREATE OR REPLACE USER 'appbroker'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT appuser TO 'appbroker'@'%';
SET DEFAULT ROLE appuser FOR 'appbroker'@'%';

CREATE OR REPLACE USER 'appsa'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  appdb.* TO 'appsa'@'%';

CREATE OR REPLACE USER 'cdbsa'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  cdb.* TO 'cdbsa'@'%';

CREATE OR REPLACE USER 'idbroker'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, LOCK TABLES, EXECUTE, TRIGGER ON cid.* TO 'idbroker'@'%';

CREATE OR REPLACE USER 'idsa'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  cid.* TO 'idsa'@'%';

CREATE OR REPLACE USER 'loggingreader'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, CREATE TEMPORARY TABLES, EXECUTE ON WTFlogs.* TO 'loggingreader'@'%';

CREATE OR REPLACE USER 'loggingsa'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER, DELETE HISTORY ON  WTFlogs.* TO 'loggingsa'@'%';

CREATE OR REPLACE USER 'loggingwriter'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT SELECT, INSERT, CREATE TEMPORARY TABLES, EXECUTE ON WTFlogs.* TO 'loggingwriter'@'%';

CREATE OR REPLACE USER 'mariabackup'@'localhost' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT LOCK TABLES, PROCESS, RELOAD, REPLICATION CLIENT ON *.* TO 'mariabackup'@'localhost';

CREATE OR REPLACE USER 'mariadb.sys'@'localhost' IDENTIFIED WITH mysql_native_password;
GRANT SELECT, UPDATE, DELETE ON TABLE mysql.global_priv TO 'mariadb.sys'@'localhost';

CREATE OR REPLACE USER 'mdbsa'@'%' IDENTIFIED WITH pam AS 'mariadb';
GRANT USAGE ON *.* TO 'mdbsa'@'%'
WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DELETE HISTORY, DROP, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'mdbsa'@'%';
GRANT appuser TO 'mdbsa'@'%' WITH ADMIN OPTION;

CREATE OR REPLACE USER 'mysql'@'localhost' IDENTIFIED WITH mysql_native_password;
GRANT USAGE ON *.* TO 'mysql'@'localhost'
WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DELETE HISTORY, DROP, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'mysql'@'localhost';

CREATE OR REPLACE USER 'sa'@'%' IDENTIFIED WITH ed25519 AS 'RIixEqeY0AdU8+tyqi24IjcT2kgI09vHJuAXvt2tUko';
GRANT USAGE ON *.* TO 'sa'@'%'
WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DELETE HISTORY, DROP, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'sa'@'%';
GRANT appuser TO 'sa'@'%' WITH ADMIN OPTION;

CREATE OR REPLACE USER 'sasmp'@'%' IDENTIFIED WITH mysql_native_password;
GRANT USAGE ON *.* TO 'sasmp'@'%'
WITH GRANT OPTION;
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DELETE HISTORY, DROP, EVENT, EXECUTE, FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER, UPDATE ON *.* TO 'sasmp'@'%';
GRANT appuser TO 'sasmp'@'%' WITH ADMIN OPTION;
