apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exchange-claim
  labels:
    component: exchange-space
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Mi
