apiVersion: v1
kind: Service
metadata:
  labels:
    app: gotenberg
  name: gotenberg
  namespace: sole-common
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31010
  selector:
    app: gotenberg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: sole-common
  labels:
    name: gotenberg
    app: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: gotenberg
        image: thecodingmachine/gotenberg:6
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: "ERROR"
        - name: GOOGLE_CHROME_IGNORE_CERTIFICATE_ERRORS
          value: "1"
        - name: DEFAULT_WAIT_TIMEOUT
          value: "1800"
        - name: MAXIMUM_WAIT_TIMEOUT
          value: "1800"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"

