apiVersion: v1
kind: Service
metadata:
  labels:
    app: mtf-production
  name: mtf-production-webapi
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mtf-production
