apiVersion: v1
kind: PersistentVolume
metadata:
  name: webcerts-store
  labels:
    component: webcerts
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//192.168.25.235/WEBCerts"
    nodeStageSecretRef:
      name: webcertscredits 
      namespace: sole-common
