---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webcerts-store
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: webcerts-store
  storageClassName: ""
